from django.core.exceptions import FieldError, FullResultSet
from django.db.models.expressions import Col
from django.db.models.sql.compiler import SQLAggregateCompiler, SQLCompiler
from django.db.models.sql.compiler import SQLDeleteCompiler as BaseSQLDeleteCompiler
from django.db.models.sql.compiler import SQLInsertCompiler
from django.db.models.sql.compiler import SQLUpdateCompiler as BaseSQLUpdateCompiler
from django.utils.functional import cached_property

__all__ = [
    "SQLAggregateCompiler",
    "SQLCompiler",
    "SQLDeleteCompiler",
    "SQLInsertCompiler",
    "SQLUpdateCompiler",
]


class SQLDeleteCompiler(BaseSQLDeleteCompiler):
    def as_sql(self):
        # Prefer the non-standard DELETE FROM syntax over the SQL generated by
        # the SQLDeleteCompiler's default implementation when multiple tables
        # are involved since MySQL/MariaDB will generate a more efficient query
        # plan than when using a subquery.
        where, having, qualify = self.query.where.split_having_qualify(
            must_group_by=self.query.group_by is not None
        )
        if self.single_alias or having or qualify:
            # DELETE FROM cannot be used when filtering against aggregates or
            # window functions as it doesn't allow for GROUP BY/HAVING clauses
            # and the subquery wrapping (necessary to emulate QUALIFY).
            return super().as_sql()
        result = [
            "DELETE %s FROM"
            % self.quote_name_unless_alias(self.query.get_initial_alias())
        ]
        from_sql, params = self.get_from_clause()
        result.extend(from_sql)
        try:
            where_sql, where_params = self.compile(where)
        except FullResultSet:
            pass
        else:
            result.append("WHERE %s" % where_sql)
            params.extend(where_params)
        return " ".join(result), tuple(params)


class SQLUpdateCompiler(BaseSQLUpdateCompiler):
    @cached_property
    def multi_table_eligible(self):
        # UPDATE FROM cannot be used when filtering against aggregates or
        # window functions as it doesn't allow for GROUP BY/HAVING clauses
        # and the subquery wrapping (necessary to emulate QUALIFY).
        having, qualify = self.query.where.split_having_qualify(
            must_group_by=self.query.group_by is not None
        )[1:]
        return having is None and qualify is None

    def as_sql(self):
        # Prefer the non-standard UPDATE FROM syntax over the SQL generated by
        # the SQLUpdateCompiler's default implementation when multiple tables
        # are involved since MySQL/MariaDB will generate a more efficient query
        # plan than when using a subquery.
        if self.multi_table_eligible and not self.query.related_updates:
            values_sql, values_params = self.get_update_values(allow_join=True)
            from_parts, from_params = self.get_from_clause()
            update_parts = [
                "UPDATE",
                *from_parts,
                "SET",
                ", ".join(values_sql),
            ]
            try:
                where_sql, where_params = self.compile(self.query.where)
            except FullResultSet:
                where_params = []
            else:
                update_parts.append("WHERE %s" % where_sql)
            update_sql = " ".join(update_parts)
            update_params = tuple([*from_params, *values_params, *where_params])
        else:
            update_sql, update_params = super().as_sql()
        # MySQL and MariaDB support UPDATE ... ORDER BY syntax.
        if self.query.order_by:
            order_by_sql = []
            order_by_params = []
            db_table = self.query.get_meta().db_table
            try:
                for resolved, (sql, params, _) in self.get_order_by():
                    if (
                        isinstance(resolved.expression, Col)
                        and resolved.expression.alias != db_table
                    ):
                        # Ignore ordering if it contains joined fields, because
                        # they cannot be used in the ORDER BY clause.
                        raise FieldError
                    order_by_sql.append(sql)
                    order_by_params.extend(params)
                update_sql += " ORDER BY " + ", ".join(order_by_sql)
                update_params += tuple(order_by_params)
            except FieldError:
                # Ignore ordering if it contains annotations, because they're
                # removed in .update() and cannot be resolved.
                pass
        return update_sql, update_params

    def execute_sql(self, *args, **kwargs):
        if (
            self.query.related_updates
            and self.multi_table_eligible
            and not self.query.order_by
        ):
            # MySQL supports multi-table updates so related update queries can
            # be combined in a single one unless aggregation is involved or that
            # any potentially related ordering is used as that would require
            # JOIN'ing against ordered subqueries which is hard to implement.
            query = self.query.clone()
            for related_update_values in query.related_updates.values():
                query.values.extend(related_update_values)
            query.related_updates = {}
            updated_rows = query.get_compiler(self.using).execute_sql(*args, **kwargs)
            # XXX: Preserve the strange return value of updated rows when MTI is
            # involved by dividing by the number of involved tables.
            updated_tables = len(self.query.related_updates)
            if self.query.values:
                updated_tables += 1
            return updated_rows // updated_tables
        return super().execute_sql(*args, **kwargs)
